### ISSUE TITLE
The tool isn't working correctly

### ISSUE THREAD

**Issue by himafareed** [BitTheByte/YouTubeShop#1]
Hello Ahmed Ezzat
Thanks for you great tool.
I found a problem in the tool that the successful logins might be 100 but the already added subs were just 20....what's wrong?

**Comment by BitTheByte** [comment]
This unpredictable behavior is cause by YouTube itself
After a while you _**MAY**_ get your subs/likes
 
But according to [Google](https://support.google.com/youtube/answer/6051134?hl=en)

> We regularly verify the legitimacy of the accounts that are subscribed to your YouTube channel. This is part of a process to ensure that our site metrics are free of spam and abuse and to keep YouTube a fair playing field for everyone. It’s important that subscriber numbers stay meaningful to ensure that, when your sub count grows, it’s because you’re building a community of real fans who will keep watching and supporting you.  

That's mean receiving your subs or likes is not guaranteed since most of them are fake
And also it depends on Emails/ComboList ,  _by using the same account frequently_  Google will consider it  as a **Fake Email**

**Comment by himafareed** [comment]
Thanks for replying
Although the bot is working there is a continuous message appearing
which is saying "no json object could be decoded" what is this?

**Comment by BitTheByte** [comment]
Can i see your log files?

**Comment by himafareed** [comment]
Excuse me, How can I get it?

**Comment by BitTheByte** [comment]
In case of fatal error a log file should be generated by the program **in the current working directory**,
If you don't have any, you haven't encounter an error.
So please let me know your steps that lead to this unknown behavior.

**Comment by himafareed** [comment]
I have made nothing. I have set-up the script on a VPS and I'm checking it
regularly but one time I saw that message and now it's filling the all page
and the main script doesn't appear

**Comment by 7soone444** [comment]
السلام عليكم
اهنيك على شغلك و استمر في ابداعك
عندي سؤال
من وين اجيب ايميلات 
@foc.cu.edu.eg

و ما هي الايميلات الي اقدر استخدمها غير هذا الايميل

اذا كان لديك الكثير من هذة الايميلات من فضلك ارسل لي اذا تستطيع

وشكرا.

**Comment by BitTheByte** [comment]
Closed for the inability to recreate the same result.
