### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by dropitlikecross** [BitTheByte/YouTubeShop#13]
Hello,

Is this a bot that will go and subscribe to other people's youtube channels based on tag or is it just an automation for loading a bunch fake accounts to sub to your channel?

**Comment by BitTheByte** [comment]
It's a automation tool to create bunch of fake subs/likes using a list of emails. However you can still re-purpose it as you like. it's an open source tool. You can use this [code](https://github.com/BitTheByte/YouTubeShop/blob/master/lib/auth.py) to authenticate to google services and this [api](https://github.com/BitTheByte/YouTubeShop/blob/master/lib/action.py) to provide the basic functionalities  for YouTube like sub/like. I hope you got the idea

I'm closing this as it's not an actual issue, feel free you reply back if you have any questions.
