### ISSUE TITLE
No lib.multi

### ISSUE THREAD

**Issue by supremethememe** [BitTheByte/YouTubeShop#16]
When built it says “Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/3BEC1A76-A719-4C7A-97CC-71709FB2CD71/Documents/noname.py", line 1, in <module>
    from lib.multi import Threader
ImportError: No module named lib.multi”

**Comment by BitTheByte** [comment]
Please run the following command and reply the response 
```
$ python --version
```

**Comment by BitTheByte** [comment]
Closed for inactivity
