### ISSUE TITLE
Failed logins

### ISSUE THREAD

**Issue by sohanzz** [BitTheByte/YouTubeShop#17]
I used python 2.7.15 as recommended but having issue with login 

![yy](https://user-images.githubusercontent.com/32102135/53699458-a5974b00-3e12-11e9-82d0-67d9b97bfca9.PNG)

**Comment by BitTheByte** [comment]
Hi @sohanzz
Thanks for reaching out to me.

Google sometimes block the login request If it's too fast or suspicious. Also i created the tool from my own device requests which includes my country so if you used accounts created at origin other than mine (which is Egypt) they might get blocked.

**Comment by sohanzz** [comment]
Any suggestion which part of the script should i tweak to adjust according to my country (Bangladesh)?

**Comment by BitTheByte** [comment]
Edit `lib/auth.py` according to your need don't forget to edit the hl parameter and the hosts

**Comment by sohanzz** [comment]
Can you guide through the process which variables should i change and how to get the correct values for my region?!

**Comment by BitTheByte** [comment]
I updated to code base to be more generic. https://github.com/BitTheByte/YouTubeShop/commit/e942de1d9341364c4e4e171f72b03e10e0c491db
You need to replace any `EG` to your county code name. use the ISO2 standard from [here](http://www.fao.org/countryprofiles/iso3list/en/)

Change `EG` at this lines:
https://github.com/BitTheByte/YouTubeShop/blob/master/lib/auth.py#L34
https://github.com/BitTheByte/YouTubeShop/blob/master/lib/auth.py#L36

**Comment by sohanzz** [comment]
I made changes and replace with my county code name in the following lines 

https://github.com/BitTheByte/YouTubeShop/blob/master/lib/auth.py#L26 
https://github.com/BitTheByte/YouTubeShop/blob/master/lib/auth.py#L34
https://github.com/BitTheByte/YouTubeShop/blob/master/lib/auth.py#L36
https://github.com/BitTheByte/YouTubeShop/blob/master/lib/auth.py#L76
https://github.com/BitTheByte/YouTubeShop/blob/master/lib/auth.py#L82

Still facing the same problem with UNAUTH
