### ISSUE TITLE
Wierd Text Issue and Coding Proble Please Check

### ISSUE THREAD

**Issue by Nitish2048** [BitTheByte/YouTubeShop#18]
![capture](https://user-images.githubusercontent.com/48296840/53909714-594d4480-4078-11e9-8faa-42b06d4aa218.JPG)

I am getting wierd text format and this error

**Comment by BitTheByte** [comment]
Python 3 support of this tool isn't ready yet please use python 2.7.15

**Comment by Nitish2048** [comment]
I tried that but i am still getting that weird text format

**Comment by BitTheByte** [comment]
if possible could you please record a video ?

**Comment by Nitish2048** [comment]
Since Now I am not on system I'll send within next 24 hrs

**Comment by BitTheByte** [comment]
Closed for inactivity
