### ISSUE TITLE
i love how poorly made this is 

### ISSUE THREAD

**Issue by DentyMods** [BitTheByte/YouTubeShop#21]
cant even fix a simple error! XD

Traceback (most recent call last):
  File "yt.py", line 84, in <module>
    threader.put(Like,[credentials[0],credentials[1],yt_id])
  File "/data/data/com.termux/files/home/YouTubeShop/lib/multi.py", line 46, in put
    for _ in xrange(self.q.qsize()): self.__t()
NameError: name 'xrange' is not defined
$

**Comment by BitTheByte** [comment]
Hi @DentyMods 

Thanks for contacting me, this tool don't fully support python 3 *yet*. the following error because `xrange` function got renamed to `range` at python 3. Please use any version of python `2.7.*` instead

**Comment by DentyMods** [comment]
oh lol sorry kinda forgot that oof

**Comment by BitTheByte** [comment]
No problem :)
Have a good day!
