### ISSUE TITLE
error Terminal 

### ISSUE THREAD

**Issue by DentyMods** [BitTheByte/YouTubeShop#22]
im getting this in my Terminal, any help?

[!] Welcome to debug mode press [CTRL+C] again to update the counters
[*] Successful logins: 50
[*] Failed logins: 0
[*] Successful actions: 0
[*] Failed actions: 46

**Comment by DentyMods** [comment]
oh nvm i forgot to save the vidoe links in action.txt sorry ^_^

**Comment by BitTheByte** [comment]
No problem .. please don't create multiple issues unless it's a necessary
if you need help please add a comment on your original issue #21
