### ISSUE TITLE
Xrange is not defined. Please help me

### ISSUE THREAD

**Issue by crypthusiast0** [BitTheByte/YouTubeShop#23]
Hello, I tried running this, but got this:

>>>                                                       <<<
>>>       __   _______   ____  _   _  ___  ____           <<<
>>>       \ \ / |_   _| / ___|| | | |/ _ \|  _ \          <<<
>>>        \ V /  | |   \___ \| |_| | | | | |_) |         <<<
>>>         | |   | |    ___) |  _  | |_| |  __/          <<<
>>>         |_|   |_|   |____/|_| |_|\___/|_|             <<<
>>>                                                       <<<
>>> ===================================================== <<<
>>> [DEV] : BitTheByte (Ahmed Ezzat)                      <<<
>>> [GitHub] : https://www.github.com/bitthebyte          <<<
>>> [Version] : 12.8.1v                                   <<<
>>> +++++++++++++++++++++++++++++++++++++++++++++++++++++ <<<
[#] Editing this banner doesn't make you a programmer :)
[Q] Choose an option (l=like , s=subscribe): l
[Q] Set number of threads [Recommended: 10]: 10
[Q] Enter accounts[Email:Password] file path: test/accounts.txt
[Q] Enter action file path: test/actions.txt
[*] Press enter to start .. 
[!] Working.. Press [CTRL + C] to access the debug mode.
Traceback (most recent call last):
  File "yt.py", line 84, in <module>
    threader.put(Like,[credentials[0],credentials[1],yt_id])
  File "/home/fmp863/Python/YouTubeShop-master/lib/multi.py", line 46, in put
    for _ in xrange(self.q.qsize()): self.__t()
NameError: name 'xrange' is not defined`

Can you please help me?

**Comment by BitTheByte** [comment]
Please refer back to #21
