### ISSUE TITLE
Error:TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by lrosal1** [BitTheByte/YouTubeShop#26]
### **return json.loads((response.content).replace(")]}'", ""))**[0][0][2]

Highlighted from auth.py does not seem to be correct. I am researching to correct it.

**Comment by BitTheByte** [comment]
Are you using python 3 ?

**Comment by lrosal1** [comment]
> Are you using python 3 ?

Yes, Using Python 3.7.

**Comment by lrosal1** [comment]
I tried using Python 2.7 But receive error message "ImportError: No module named path" when attempting to install the (path module) it's not available for Python 2.7. Still looking it to it further. Looking through the code piece by piece.

**Comment by BitTheByte** [comment]
May you please try python 2.7.16 ?

**Comment by lrosal1** [comment]
Created python 2.7.16 virtualenv, now when running this is the error message being received.

 from os.path import (curdir, pardir, sep, pathsep, defpath, extsep, altsep, devnull)
ImportError: No module named path.

When attempting to pip install (path) it doesn't exist in a package. Still researching to see if I can figure this out.

**Comment by BitTheByte** [comment]
I believe your Python 2.7 installation is somehow corrupted since there is not module named path is being used at the whole code base. You could run the code for example on any online Python environment like repl.it to verify if the problem is from the code or your python installation

**Comment by lrosal1** [comment]
I believe that it's kind of odd that the Python Version 2.7.16 is corrupted, I did try on 2 different machines with the same result of error message. I will try on an online IDE and see what happens.

**Comment by BitTheByte** [comment]
Please post the steps you have used in order for me to recreate the issue

**Comment by lrosal1** [comment]
Steps taken.

Step 1: Cloned the project to local machine.
Step 2: Created virtualenv with Python version 2.7.16 with YouTube_SubBot folder for the project name.
Step 3: Copied all files from the cloned folder into the root folder of the project (YouTube_SubBot).
Step 4: Installed all necessary packages required:
Packages:
colorama
requests

Step 5: Since modules multi, auth, exception, action and cli were in the lib cloned folder when copying and pasting them into the root folder of the project they were automatically pasted into the Lib folder that was created when creating the virtualenv with python 2.7.16 with all the pre-installed packages that come with the python version.

Step 6:  since the folder was no longer called (lib) with lower case letters but (Lib) with uppercase had to update the import code from the code on the yt.py file to re-present the new folder as follows.

from **Lib**.multi import Threader
from **Lib**.auth import GAuth
import **Lib**.execption as err
import **Lib**.action as YT
import **Lib**.cli as cli

I haven't given up yet, still attempting to figure it out on my end as well.

I have done research and what keeps popping up is there being some type of conflict with os.py as if I had another file with that name. I have searched the my structure tree and don't see that name anywhere else in my structure, so still attempting to figure out.

**Comment by BitTheByte** [comment]
I understand that you're having some sort of conflict with virtualenv and this project.

I've searched online for a solution for the error message below and it seems it's a very common error 
```
from os.path import (curdir, pardir, sep, pathsep, defpath, extsep, altsep, devnull)
ImportError: No module named path.
```
Found a solution to it on https://stackoverflow.com/questions/47891332/importerror-no-module-named-path
Could you please try this command?
```
$ pip install path.py
```

**Comment by BitTheByte** [comment]
I'm unable to recreate your issue as you described it. so here the list of commands i used on my device  

```
OS: Windows 10 Version 1809
Python Version: 2.7.16
```
1) pip install virtualenv
2) mkdir myproject
3) virtualenv -p C:\Python27\python.exe myproject
4) cd myproject
5) virtualenv env
6) env\Scripts\activate.bat
7) git clone https://github.com/BitTheByte/YouTubeShop
8) cd YouTubeShop
9) pip install requests
10) pip install colorama
11) python yt.py

Running step n.11 resulted in project launching successfully.

**Comment by lrosal1** [comment]
Thank you, Trying this now.

**Comment by lrosal1** [comment]
Thank you, I was able to get this completed.

**Comment by BitTheByte** [comment]
Shall we close this issue?

**Comment by lrosal1** [comment]
Yes, sorry. Closing it.
