### ISSUE TITLE
No Results - Failing Logins/Actions 

### ISSUE THREAD

**Issue by y331625nwytg** [BitTheByte/YouTubeShop#28]
If you have one account and you have lets say 16 youtube channels on it. Will it sub/like with all those 16 channels on your one account? 
Thanks in advance for answering

**Comment by BitTheByte** [comment]
In theory Yes this should be possible However due to Google's security measures the account like/sub may get cancelled starting from the 10th or 9th account that is why i suggest  using multiple accounts to lower to chance of Google noticing suspicious activity

**Comment by y353220nwytg** [comment]
Hey thanks for your reaction.
Will it automatically loop through the 8 accounts if I add 7 extra? @BitTheByte

Also I just try with one and the debug said:
[*] Successful logins: 1
[*] Failed logins: 0
[*] Successful actions: 0
[*] Failed actions: 0

[DEBUG-MODE] Like: [hidden@gmail.com:hidden]:LOGGED -> hiddenid:0

But the like was not added. Same for the sub. Am I doing something wrong? I am 100% sure the id was correct.

**Comment by towuk118** [comment]
+++ conect this quest

**Comment by BitTheByte** [comment]
Hello @y331625nwytg 

Sorry for the late response. I believe your issue should be fixed at the current version [12.8.2] may you please confirm that?
