### ISSUE TITLE
script keep loading 

### ISSUE THREAD

**Issue by icodzz** [BitTheByte/YouTubeShop#3]
hi i tested your script  ! 
its keep loading 
[+] Successful Logins   = 0
[!] Failed Logins       = 0
with 0 result :/

**Comment by BitTheByte** [comment]
Please do the following:
- Check your internet connection
- Check if you can access Google/YouTube properly 
- Check if any logs are generated , if so please send them over here
- Lower the number of threads or use the default value
- Run the .py using known working [email:password] as a test
__please note that the speed of action depends on your internet connection speed__
