### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by DasteS** [BitTheByte/YouTubeShop#30]
Hi, when i launch yt.py it says this:
>>> ===================================================== <<<
>>>                                                       <<<
>>>       __   _______   ____  _   _  ___  ____           <<<
>>>       \ \ / |_   _| / ___|| | | |/ _ \|  _ \          <<<
>>>        \ V /  | |   \___ \| |_| | | | | |_) |         <<<
>>>         | |   | |    ___) |  _  | |_| |  __/          <<<
>>>         |_|   |_|   |____/|_| |_|\___/|_|             <<<
>>>                                                       <<<
>>> ===================================================== <<<
>>> [DEV] : BitTheByte (Ahmed Ezzat)                      <<<
>>> [GitHub] : https://www.github.com/bitthebyte          <<<
>>> [Version] : 12.8.2v                                   <<<
>>> +++++++++++++++++++++++++++++++++++++++++++++++++++++ <<<
[#] Editing this banner doesn't make you a programmer :)

Traceback (most recent call last):
  File "C:\Users\Daste\Desktop\YouTubeShop-master\yt.py", line 10, in <module>
    action             = cli.ask_action()
  File "C:\Users\Daste\Desktop\YouTubeShop-master\lib\cli.py", line 85, in ask_action
    C3=colorama.Fore.LIGHTCYAN_EX,
AttributeError: 'AnsiCodes' object has no attribute 'LIGHTCYAN_EX'

Please help. Thx

**Comment by towuk118** [comment]
do you use python 2.7?

**Comment by towuk118** [comment]
install requireds?

**Comment by DasteS** [comment]
No im using phyton 3.7.3

**Comment by DasteS** [comment]
Should I downgrade phyton to 2.7?

**Comment by BitTheByte** [comment]
Hey @DasteS 
 Yes, please use Python 2.7

**Comment by BitTheByte** [comment]
Closed for inactivity
