### ISSUE TITLE
Why this?

### ISSUE THREAD

**Issue by Ukhuy** [BitTheByte/YouTubeShop#31]
![IMG_20190719_005325](https://user-images.githubusercontent.com/53055533/61476425-a1ce2480-a9bf-11e9-963d-d5a7303ade14.jpg)

i am cant login :"v and i do what ur way.

**Comment by BitTheByte** [comment]
Correct me if I'm wrong as I'm trying to do my best to understand your situation here, I believe you're having trouble with the combo file. Could you please tell me what is your files structure? Also have you tried writing the full path to the file instead of the relative one?

**Comment by BitTheByte** [comment]
Closed for inactivity
