### ISSUE TITLE
idk what to say as error

### ISSUE THREAD

**Issue by NameNotTakenYAY** [BitTheByte/YouTubeShop#32]
>>> ===================================================== <<<
>>>                                                       <<<
>>>       __   _______   ____  _   _  ___  ____           <<<
>>>       \ \ / |_   _| / ___|| | | |/ _ \|  _ \          <<<
>>>        \ V /  | |   \___ \| |_| | | | | |_) |         <<<
>>>         | |   | |    ___) |  _  | |_| |  __/          <<<
>>>         |_|   |_|   |____/|_| |_|\___/|_|             <<<
>>>                                                       <<<
>>> ===================================================== <<<
>>> [DEV] : BitTheByte (Ahmed Ezzat)                      <<<
>>> [GitHub] : https://www.github.com/bitthebyte          <<<
>>> [Version] : 12.8.2v                                   <<<
>>> +++++++++++++++++++++++++++++++++++++++++++++++++++++ <<<
[#] Editing this banner doesn't make you a programmer :)

[32m[Q] [36mChoose an option ([96ml=like [37m, [96ms=subscribe[36m): 1
[E] Please choose a valid option
[32m[Q] [36mChoose an option ([96ml=like [37m, [96ms=subscribe[36m): 2
[E] Please choose a valid option
[32m[Q] [36mChoose an option ([96ml=like [37m, [96ms=subscribe[36m): 3
[E] Please choose a valid option
[32m[Q] [36mChoose an option ([96ml=like [37m, [96ms=subscribe[36m): 4
[E] Please choose a valid option
[32m[Q] [36mChoose an option ([96ml=like [37m, [96ms=subscribe[36m): 5
[E] Please choose a valid option
[32m[Q] [36mChoose an option ([96ml=like [37m, [96ms=subscribe[36m): 96ms
[E] Please choose a valid option
[32m[Q] [36mChoose an option ([96ml=like [37m, [96ms=subscribe[36m):

**Comment by BitTheByte** [comment]
Please don't copy the options just type them

**Comment by BitTheByte** [comment]
Closed for inactivity
