### ISSUE TITLE
[DEBUG-MODE] Like: [(MyEmail):(MyPass)]:UNAUTH -> r0IXkZQZfoU:0

### ISSUE THREAD

**Issue by akib2002** [BitTheByte/YouTubeShop#34]
I am facing this error in debug mode,
[DEBUG-MODE] Like: [(Email):(Pass)]:UNAUTH -> r0IXkZQZfoU:0

my mail pass is accurate and i can login with these credentials, why this error spiking then?

**Comment by ticky520** [comment]
me too.

**Comment by BitTheByte** [comment]
Sorry for the delay, I'll be looking at this in the next few days. I'll keep you updated

**Comment by BitTheByte** [comment]
This should be fixed now. feel free to reopen this if you're still unable to login
