### ISSUE TITLE
I'm getting this error! help me please thank you

### ISSUE THREAD

**Issue by pikeoboo** [BitTheByte/YouTubeShop#37]
Traceback (most recent call last):
  File "C:\Users\pike\Desktop\YouTubeShop-master\yt.py", line 2, in <module>
    from lib.auth import GAuth
  File "C:\Users\pike\Desktop\YouTubeShop-master\lib\auth.py", line 1, in <module>
    import requests
ImportError: No module named requests

**Comment by BitTheByte** [comment]
Please install the required libraries first
```
python -m pip install -r requirements.txt

**Comment by Mastersam07** [comment]
You can `pip install requests` before running this application

**Comment by Mastersam07** [comment]
I don't seem to find a requirements file for this

**Comment by pikeoboo** [comment]
I feel like I'm not understanding what to do! could you able to help me a bit more :) sorry

**Comment by pikeoboo** [comment]
I think I got it thanks :)

**Comment by BitTheByte** [comment]
This should be fixed now. feel free to reopen this if you're still unable to login
