### ISSUE TITLE
name 'xrange' is not defined

### ISSUE THREAD

**Issue by subhampro** [BitTheByte/YouTubeShop#39]
DevTools listening on ws://127.0.0.1:57376/devtools/browser/8dbed15e-aefb-45c5-86fc-e5b71a26c881
Traceback (most recent call last):
  File "C:\Users\prosu\Downloads\YouTubeShop-master\yt.py", line 96, in <module>
    threader.put(subscribe_wrapper,[credentials[0],credentials[1],identifier])
  File "C:\Users\prosu\Downloads\YouTubeShop-master\lib\multi.py", line 43, in put
    for _ in xrange(self.q.qsize()): self.__t()
NameError: name 'xrange' is not defined

**Comment by BitTheByte** [comment]
Please use Python 2 as xrange is renamed to range in Python 3

**Comment by subhampro** [comment]
i am not able to find a stable ver of Python 2.0 ! can you share link ?

**Comment by BitTheByte** [comment]
Download the **latest** Python 2 version from the official website https://python.org

**Comment by BitTheByte** [comment]
I'm closing this for now, feel free to reopen if the issue continues.

**Comment by ghost** [comment]
The problem is still exists even on python2

**Comment by ghost** [comment]
> The problem is still exists even on python2

![image](https://user-images.githubusercontent.com/87362984/128062349-8d447d99-fedc-48c3-9465-c7879fc832a7.png)
