### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by gustavop-ferreira** [BitTheByte/YouTubeShop#41]
I tried to run the Script, I came across it in Python 2.7, downloaded it, created a new path, ran it with python2 yt.py, until then, everything normal, opened Selenium, went to the Google page and stayed there, I didn't write anything or anything, it just counted as a login error. How can I solve?

**Comment by BitTheByte** [comment]
Hello @gustavop-ferreira 

If you're positive you're using a valid account please DM me over twitter [@BitTheByte](https://twitter.com/BitTheByte) example from your emails list. I'll reopen this issue if needed
