### ISSUE TITLE
get eror

### ISSUE THREAD

**Issue by BlacksoftEvolution** [BitTheByte/YouTubeShop#43]
DevTools listening on ws://127.0.0.1:50775/devtools/browser/88dc642e-5520-4f08-b8ef-ed5eb0b2c98a
Traceback (most recent call last):
  File "yt.py", line 96, in <module>
    threader.put(subscribe_wrapper,[credentials[0],credentials[1],identifier])
  File "E:\YT PY\YouTubeShop\lib\multi.py", line 43, in put
    for _ in xrange(self.q.qsize()): self.__t()
NameError: name 'xrange' is not defined

**Comment by BitTheByte** [comment]
Please use python 2 not 3 #39

**Comment by BlacksoftEvolution** [comment]
oh sorry, v 2.7.17?

**Comment by BitTheByte** [comment]
Yes, any version under 2.7.* should work

**Comment by BlacksoftEvolution** [comment]
oke thank you

**Comment by BlacksoftEvolution** [comment]
Whats wrong?
 
[!] Welcome to YoutubeShop dashboard
[*] Successful logins: 0
[*] Failed logins: 20
[*] Successful actions: 0
[*] Failed actions: 0

[CORE]: shutting down chrome ..  please wait

E:\YT PY\YouTubeShop>
