### ISSUE TITLE
the tool not work

### ISSUE THREAD

**Issue by a7mednegm** [BitTheByte/YouTubeShop#5]
tool does not work properly
Even after modifying the email list
Please update
Thank you for the wonderful work

**Comment by BitTheByte** [comment]
Mind giving me some details on the following? 
- what kind of behavior do you get?
- is there any errors/warnings? 
- what's your os?
- what kind of emails do you use?
- are you sure that the emails even working?
- are you using vpn?
- what's your test case and the behavior you expect from the tool?

**Comment by BitTheByte** [comment]
Closed for inactivity
