### ISSUE TITLE
a bytes-like object is required not 'str'

### ISSUE THREAD

**Issue by ghost** [BitTheByte/YouTubeShop#53]
Ok let me say that the bot is actually great, and im not saying this to get your attention! It's really so good!

However I am facing an error that says - a bytes-like object is required, not 'str' on line return json.loads((response.content).replace(")]}'",""))[0][0][2].encode()

have any idea on how to fix this?

By the way if you ever need anything make sure to hmu on discord TOG6#6666!

Have a good day then ig?

**Comment by BitTheByte** [comment]
Hi @TOG6-6 

You already got my attention by this :) This project is not maintained currently and will not function however the solution to your problem is to use python 2.7.*
