### ISSUE TITLE
Convert to python 3

### ISSUE THREAD

**Issue by geper** [BitTheByte/YouTubeShop#6]
Hello
I converted script to python 3 and get error
E] G_identifier:expected bytes, bytearray or buffer compatible object
screen error https://prnt.sc/l1rolp
 
thank help me

**Comment by BitTheByte** [comment]
Thanks a lot i'll test your code and merge it soon
again thanks for your help

**Comment by geper** [comment]
Hi
You released the code.
I wrote about a mistake. Error exists.
E] G_identifier:expected bytes, bytearray or buffer compatible object
maybe you can tell me why this error is happening. I can't figure it out
*] Setect the name of your [Email:Password] Combo file: youtubegmail.txt this file where loginn and passwword gmail
*] Setect the name of your [YouTube] Combo file: this youtube channel link 
what am I doing wrong?
You can write a description. It is not clear what happens in the code:?
 Thank

**Comment by geper** [comment]
hi
Yes, after adding the encoding identifier there are no errors, but now the other nonsense nothing happens
screen
http://prntscr.com/l3zc0d
subscription does not occur he stupidly thinks nothing happens
I can provide teamviewer if you have time.
And you can still make it out as if many youtube accounts on one mail are not indicated anywhere
thank

**Comment by BitTheByte** [comment]
Not receiving the subs/likes actually is already known bug see https://github.com/BitTheByte/YouTubeShop/issues/1
However i have no clue how to fix it except sending the like/sub request multiple times which will effect the speed and preformance. But i'm implementing it as an optional feature soon, until finding a better way to do it

**Comment by BitTheByte** [comment]
Since the original problem is solved i'm closing this issue
Thanks for your contribution ⭐️

**Comment by geper** [comment]
hi  BitTheByte 
if many youtube accounts on one mail are not indicated anywhere
thank
