### ISSUE TITLE
YoutubeShop3 Not Running

### ISSUE THREAD

**Issue by chaule97** [BitTheByte/YouTubeShop#9]
hi BitTheByte!
I try to run YoutubShop3 but when programe run to "[+] All Done! , Press Enter to start .." It cannot continue. Can you explain me? Thankyou

**Comment by BitTheByte** [comment]
Do have any empty any lines in your txt files?

**Comment by BitTheByte** [comment]
I'll check on it today. in the mean time check the py2 version is it working or giving the same result ?

**Comment by BitTheByte** [comment]
@chaule97 i didn't get the same result
Try uninstalling requests and install this version `2.19.1`
```
pip install requests==2.19.1
```
- Do you have any kind of proxy installed ? 
- What's your python version ? l.e `3.x.xx`
- Are you using x64 or x86 ? 
- Are any `.txt` files (logs) generated ? 
- Are you using the latest version of this tool?
- Is there any errors ?   

Can you also please provide a video?

**Comment by BitTheByte** [comment]
Closed for inactivity
